import { useEffect, useState } from "react";
import { api, BACKEND_URL } from "@/lib/api";
import { ANALYSTS, ANALYST_ORDER } from "@/lib/config";
import { Check, Play, Pause, RefreshCw } from "lucide-react";
import { toast } from "sonner";

export default function VoiceLab() {
  const [manifest, setManifest] = useState({});
  const [loading, setLoading] = useState(true);
  const [selecting, setSelecting] = useState({}); // {analyst_id: bool}
  const [selected, setSelected] = useState({}); // {analyst_id: preview_index}
  const [playing, setPlaying] = useState(null); // url currently playing
  const [audioEl] = useState(() => new Audio());

  useEffect(() => {
    api
      .get("/voice-lab/manifest")
      .then((r) => setManifest(r.data.characters || {}))
      .catch((e) => console.error(e))
      .finally(() => setLoading(false));
    return () => {
      audioEl.pause();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const togglePlay = (url) => {
    if (playing === url) {
      audioEl.pause();
      setPlaying(null);
      return;
    }
    audioEl.pause();
    audioEl.src = `${BACKEND_URL}${url}`;
    audioEl.onended = () => setPlaying(null);
    audioEl.play().then(() => setPlaying(url)).catch((e) => {
      console.error("play failed", e);
      toast.error("Couldn't play — click again");
    });
  };

  const selectPreview = async (analystId, previewIndex) => {
    setSelecting((s) => ({ ...s, [analystId]: true }));
    try {
      const r = await api.post("/voice-lab/select", {
        analyst_id: analystId,
        preview_index: previewIndex,
      });
      setSelected((s) => ({ ...s, [analystId]: previewIndex }));
      toast.success(
        `${r.data.voice_name} voice locked in. Cleared ${r.data.cleared_cache_files} cached lines — head to Home to hear it.`,
      );
    } catch (e) {
      toast.error("Selection failed: " + (e?.response?.data?.detail || e.message));
    } finally {
      setSelecting((s) => ({ ...s, [analystId]: false }));
    }
  };

  if (loading) return <div className="text-white/60 py-8">Loading preview candidates…</div>;

  return (
    <div>
      <div className="mb-8">
        <div className="font-accent text-xs uppercase tracking-[0.35em] text-[#1e5dff]">
          Voice Casting Room
        </div>
        <h1 className="font-headline text-4xl sm:text-5xl text-white mt-1">
          Pick each analyst's voice
        </h1>
        <p className="text-white/60 mt-2 max-w-2xl">
          Three candidates per character were generated by ElevenLabs from your
          detailed briefs. Play each, pick the one that feels right, and it
          becomes that analyst's permanent voice on the desk. The banter cache
          clears automatically so the next Home visit uses the new voice.
        </p>
      </div>

      <div className="space-y-8">
        {ANALYST_ORDER.map((id) => {
          const a = ANALYSTS[id];
          const char = manifest[id];
          if (!char || !char.previews) return null;
          const chosen = selected[id];
          return (
            <div
              key={id}
              className="card-surface p-5"
              style={{ borderColor: `${a.accent}44` }}
              data-testid={`voice-lab-char-${id}`}
            >
              <div className="flex items-center gap-3 mb-2">
                <div
                  className="h-3 w-3 rounded-full"
                  style={{ background: a.accent, boxShadow: `0 0 12px ${a.accent}` }}
                />
                <h2 className="font-headline text-2xl text-white">{a.name}</h2>
                <div className="ml-auto text-xs font-accent uppercase tracking-widest text-white/40">
                  {a.role}
                </div>
              </div>
              <p className="text-white/60 text-sm leading-relaxed mb-4 max-w-3xl">
                {char.description}
              </p>

              <div className="grid sm:grid-cols-3 gap-3">
                {char.previews.map((p) => {
                  const isPlaying = playing === p.url;
                  const isChosen = chosen === p.index;
                  return (
                    <div
                      key={p.index}
                      className="rounded-lg border p-4 flex flex-col gap-3"
                      style={{
                        borderColor: isChosen ? a.accent : "#2d2d35",
                        background: isChosen ? `${a.accent}11` : "#0b0b10",
                      }}
                    >
                      <div className="flex items-center justify-between">
                        <div className="font-accent text-xs uppercase tracking-widest text-white/60">
                          Candidate {p.index}
                        </div>
                        {isChosen && (
                          <div
                            className="flex items-center gap-1 text-xs font-accent uppercase tracking-widest"
                            style={{ color: a.accent }}
                          >
                            <Check className="w-3.5 h-3.5" />
                            Chosen
                          </div>
                        )}
                      </div>

                      <button
                        onClick={() => togglePlay(p.url)}
                        data-testid={`voice-play-${id}-${p.index}`}
                        className="inline-flex items-center justify-center gap-2 h-10 rounded-md bg-[#0d0d11] hover:bg-[#181820] border border-[#2d2d35] text-white font-accent text-xs uppercase tracking-widest transition-colors"
                      >
                        {isPlaying ? (
                          <>
                            <Pause className="w-4 h-4" />
                            Pause
                          </>
                        ) : (
                          <>
                            <Play className="w-4 h-4" />
                            Play
                          </>
                        )}
                      </button>

                      <button
                        onClick={() => selectPreview(id, p.index)}
                        disabled={selecting[id]}
                        data-testid={`voice-select-${id}-${p.index}`}
                        className="h-10 rounded-md text-white font-accent text-xs uppercase tracking-widest disabled:opacity-40 transition-colors"
                        style={{
                          background: isChosen ? a.accent : "transparent",
                          color: isChosen ? "#0d0d11" : "#fff",
                          border: `1px solid ${a.accent}`,
                        }}
                      >
                        {selecting[id] ? (
                          <span className="inline-flex items-center gap-1">
                            <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                            Locking…
                          </span>
                        ) : isChosen ? (
                          "This one"
                        ) : (
                          "Pick this voice"
                        )}
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
